# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudlyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classes',
            new_name='SchoolClasses',
        ),
    ]
